name: C/C++ CI (x86/vac/hw-operations-in-vac-v3)

on:
  push:
    branches: [ "x86/vac/hw-operations-in-vac-v3" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: config (default)
      run:  wget https://gist.githubusercontent.com/vsrinivas/09eebe43a305c46145d810c23bb0d996/raw/0c285468549e43263efabed0f8b469309f0517fb/gistfile1.txt -O .config
    - name: make mrproper (default)
      run: make mrproper
    - name: make (default)
      run: make CC="ccache cc" -j`nproc` && make CC="ccache cc" -j`nproc` modules
    - name: config (minimal)
      run: wget https://gist.githubusercontent.com/vsrinivas/125460123140af2c2c1f0e0fd4cab874/raw/539994b4b8905300f62f78324a13e3e4bed09cfe/gistfile1.txt -O .config
    - name: make mrproper (minimal)
      run: make mrproper
    - name: make (minimal)
      run: make CC="ccache cc" -j`nproc` && make CC="ccache cc" M=arch/x86/kvm modules
